### ISSUE TITLE
Assignment 02 -- 28 Feb 2024

### ISSUE THREAD

**Issue by dudung** [dudung/fi6004-01-2023-2#2]
+ Practice materials on previous slide on a notebook.
+ Share the notebook as a gist.
+ Put link of the gist here.

**Comment by gitaameliiaa** [comment]
I choose FFT in generator wave, here is the gist link https://gist.github.com/gitaameliiaa/15491e19a8fbe19be1cffd1bf6c01e66

**Comment by denikaryono** [comment]
Here are my gist links for audio and image fft
- https://gist.github.com/denikaryono/ed539c85c82c74569498546ee1818a6d
- https://gist.github.com/denikaryono/c4ddf921851785adbdfb42959bdf007d

**Comment by denikaryono** [comment]
Here is my gist link for Python list
https://gist.github.com/denikaryono/f2d622bedfe1434d87e674c4c6bf02cb

**Comment by halserach** [comment]
These are some gists related to the Assignment 2.

Gist for Image and Audio FFT: https://gist.github.com/halserach/6db6813d3f0d3e587d7135540916e4bd
Gist contains exercises from Python List slide: https://gist.github.com/halserach/8f014f322f1589c246c3c9533e1f5ce1
